# Generated by Django 5.1.4 on 2024-12-09 13:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article_writing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
