# Generated by Django 5.1.4 on 2024-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article_writing", "0002_alter_article_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(),
        ),
    ]
