# Generated by Django 5.1.4 on 2024-12-08 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "phone_no",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("PMDC_no", models.CharField(max_length=20, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_authorized", models.BooleanField(default=False)),
                ("degree", models.CharField(max_length=100)),
                ("institute", models.CharField(max_length=150)),
                ("designation", models.CharField(max_length=100)),
                ("hospital_clinic", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=100)),
                ("hospital_name", models.CharField(max_length=150)),
                ("review_address", models.TextField()),
                ("practice_days", models.JSONField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("fee", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "assistant_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assistant_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("online_days", models.JSONField()),
                ("online_start_time", models.TimeField()),
                ("online_end_time", models.TimeField()),
                (
                    "online_consultation_fee",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="doctor_pictures/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "phone_no",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{10,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
